"""empty message

Revision ID: e0ddef51aebf
Revises: f29bad18a43a
Create Date: 2019-12-06 20:40:47.399504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0ddef51aebf'
down_revision = 'f29bad18a43a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'date')
    # ### end Alembic commands ###
